FROM amazoncorretto:11
MAINTAINER Douglas Chinwuba <cemekadouglas@yahoo.com>

ADD target/notification-service.jar notification-service.jar
ENTRYPOINT ["java", "-jar", "/notification-service.jar"]

EXPOSE 8084