spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://localhost/expense_tracker?useSSL=false
    username: user
    password: test123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

expenseTracker:
  jwt:
    secretKey: secret
    expirationMs: 86400000

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
