spring:
  datasource:
    url: jdbc:postgresql://ep-super-mode-742008.us-east-2.aws.neon.tech/neondb
    username: douglaschinwuba10
    password: c8pkvslXbiP5
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

expenseTracker:
  jwt:
    secretKey: secret

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      hostname: localhost

logging:
  level:
    org:
      hibernate:
        type: trace