spring:
  datasource:
    url: jdbc:postgresql://ep-super-mode-742008.us-east-2.aws.neon.tech/neondb
    username: douglaschinwuba10
    password: c8pkvslXbiP5
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

expenseTracker:
  jwt:
    secretKey: secret
    expirationMs: 86400000

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: AUTH-SERVICE
