spring:
  datasource:
    url: jdbc:postgresql://ep-super-mode-742008.us-east-2.aws.neon.tech/neondb
    username: douglaschinwuba10
    password: c8pkvslXbiP5
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084

expenseTracker:
  jwt:
    secretKey: secret
  notification:
    email: "expensetrackernotification@gmail.com"
    password: "expenseapp"

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true

notify:
  cron: 0 0 12 * * 6

